services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Institution\Controller\:
        resource: '../../src/Institution/Controller/*'
        tags: ['controller.service_arguments']

    # TODO: Instead of building OpenSkosIriFactory we can create dedicate InstitutionIriFactory
    # To cover all our needs
    institution.iri_factory:
        class: App\OpenSkos\OpenSkosIriFactory
        arguments:
            $namespace: 'http://tenant'

    App\Institution\Sparql\SparqlInstitutionRepository:
        arguments:
            $iriFactory: '@institution.iri_factory'

    App\Institution\InstitutionRepository: '@App\Institution\Sparql\SparqlInstitutionRepository'
    