services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Institution\Controller\:
        resource: '../../src/Institution/Controller/*'
        tags: ['controller.service_arguments']

    App\Institution\Sparql\SparqlInstitutionRepository: ~

    App\Institution\InstitutionRepository: '@App\Institution\Sparql\SparqlInstitutionRepository'

