services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Set\Controller\:
        resource: '../../src/Set/Controller/*'
        tags: ['controller.service_arguments']

    App\Set\SetRepository: '@App\Set\Sparql\SparqlSetRepository'


