parameters:
  ontology.openskos:
    name: OpenSkos
    prefix: openskos
    namespace: 'http://openskos.org/xmlns#'
    hasVocabulary: true
    properties:
      tenant:
        "rdf:type":
          - "owl:ObjectProperty"
      status:
        "rdf:type":
          - "owl:ObjectProperty"
      toBeChecked:
        "rdf:type":
          - "owl:ObjectProperty"
      dateDeleted:
        "rdf:type":
          - "owl:ObjectProperty"
      deletedBy:
        "rdf:type":
          - "owl:ObjectProperty"
      acceptedBy:
        "rdf:type":
          - "owl:ObjectProperty"
      modifiedBy:
        "rdf:type":
          - "owl:ObjectProperty"
      uuid:
        "rdf:type":
          - "owl:ObjectProperty"
      set:
        "rdf:type":
          - "owl:ObjectProperty"
      role:
        "rdf:type":
          - "owl:ObjectProperty"
      inSkosCollection:
        "rdf:type":
          - "owl:ObjectProperty"
      code:
        "rdf:type":
          - "owl:ObjectProperty"
      name:
        "rdf:type":
          - "owl:ObjectProperty"
      disableSearchInOtherTenants:
        "rdf:type":
          - "owl:ObjectProperty"
      enableStatussesSystem:
        "rdf:type":
          - "owl:ObjectProperty"
      allow_oai:
        "rdf:type":
          - "owl:ObjectProperty"
      oai_baseURL:
        "rdf:type":
          - "owl:ObjectProperty"
      conceptBaseUri:
        "rdf:type":
          - "owl:ObjectProperty"
      licenceURL:
        "rdf:type":
          - "owl:ObjectProperty"
      webpage:
        "rdf:type":
          - "owl:ObjectProperty"
      enableskosxl:
        "rdf:type":
          - "owl:ObjectProperty"
      notationuniquepertenant:
        "rdf:type":
          - "owl:ObjectProperty"
      notationautogenerated:
        "rdf:type":
          - "owl:ObjectProperty"
      usertype:
        "rdf:type":
          - "owl:ObjectProperty"
      apikey:
        "rdf:type":
          - "owl:ObjectProperty"


      isReplacedBy:
        "rdf:type":
          - "owl:ObjectProperty"
      replaces:
        "rdf:type":
          - "owl:ObjectProperty"
      inCollection:
        "rdf:type":
          - "owl:ObjectProperty"
      inSet:
        "rdf:type":
          - "owl:ObjectProperty"

    const:
      statuses:
        type: list
        source: status

    status:
      - candidate
      - approved
      - redirected
      - not_compliant
      - rejected
      - obsolete
      - deleted
